### ISSUE TITLE
Error with GaussianBlur

### ISSUE THREAD

**Issue by caiqi** [open-mmlab/mmselfsup#62] opened 2020-10-29 06:01 UTC
The latest torchvision has implemented GaussianBlur (https://github.com/pytorch/vision/commit/4106dbb864ce94e5003ef888ba23c59cc9c5ce31). The current code will cause an error due to duplicate registration of GaussianBlur. Would it be better to use torchvision's GaussianBlur or change the name of GaussianBlur in this repo？

**Comment by rugrag** [comment] 2020-10-29 10:33
Same issue here!

**Comment by XiaohangZhan** [comment] 2020-10-29 14:18
Fixed by avoiding registering GaussianBlur from torchvision. Since torchvision's GaussianBlur is not verified to reproduce the results, we prefer to use the previous one. I cannot test it since my torchvison version is low, could please check if the issue is fixed?

**Comment by rugrag** [comment] 2020-10-30 15:22
now it works! thanks

**Closed as completed** 2020-10-30 15:31 UTC
